//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Issue12Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Issue12Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.Issue12Resources", typeof(Issue12Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ByRefRoListOfIssue13StampTestPacketV2H0oy0p xmlns=&quot;http://schemas.datacontract.org/2004/07/UnitTests&quot; xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;_array&gt;&lt;Issue13StampTestPacket&gt;&lt;_acqSysRefTicks&gt;6786159194&lt;/_acqSysRefTicks&gt;&lt;_acqSysTicksPerSecond&gt;2441422&lt;/_acqSysTicksPerSecond&gt;&lt;_acquiredSystemWallClockDateTime&gt;2021-07-17T17:53:59.6695867-04:00&lt;/_acquiredSystemWallClockDateTime&gt;&lt;_portableCastFromMonotonic xmlns:a=&quot;http://schemas.datacontract.org/2004/07/HpTimeStamps&quot;&gt;&lt;a:_dateTimeNanosecondOffsetFromM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Win10x64_2_441_442_tps_2021_07_17T17_53_59_6774022_04_00 {
            get {
                return ResourceManager.GetString("Win10x64_2_441_442_tps_2021_07_17T17_53_59_6774022_04_00", resourceCulture);
            }
        }
    }
}
